name: 'Render Benchmark Results'
description: 'Renders vitest benchmark results as markdown in GitHub step summary'
inputs:
  benchmark-file:
    description: 'Path to the vitest benchmark JSON output file'
    required: true
  world-name:
    description: 'Name of the world being benchmarked'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Render benchmark results
      shell: bash
      run: |
        node ${{ github.action_path }}/render.js "${{ inputs.benchmark-file }}" "${{ inputs.world-name }}" >> $GITHUB_STEP_SUMMARY
